version: 2

sources:
  - name: ads
    tables:
      - name: ads_install
      - name: web_analytics_cohorts_v4
      - name: referral_payout_stats
      - name: referral_reference_stats
      - name: referral_bloggers
      - name: device_advertising_costs
      - name: web_analytics_pageviews_with_segments
  - name: mart
    tables:
      - name: dim_device_min
      - name: dim_region
      - name: device_events
      - name: dim_published_variant
      - name: product_rating_counters
      - name: star_order_2020
      - name: star_active_device
      - name: category_levels
      - name: dim_published_product_min
      - name: core_review_quiz_answers_scd2
      - name: babylone_events
      - name: fact_order_2020
      - name: link_device_real_user
      - name: published_products_current
      - name: onfy_babylone_events
      - name: dim_currency_rate
  - name: mongo
    tables:
      - name: core_categories_daily_snapshot
      - name: core_experiments_daily_snapshot
      - name: core_stores_daily_snapshot
      - name: events_ad_spent_internal_daily_snapshot
      - name: events_ad_partners_daily_snapshot
      - name: core_tracking_providers_daily_snapshot
      - name: core_merchants_daily_snapshot
      - name: b2b_core_users_daily_snapshot
      - name: b2b_core_admin_users_daily_snapshot
      - name: b2b_core_variant_appendixes_daily_snapshot
      - name: b2b_core_published_products_daily_snapshot
      - name: b2b_core_published_variants_daily_snapshot
      - name: b2b_core_product_states_daily_snapshot
      - name: b2b_core_product_appendixes_daily_snapshot
      - name: b2b_core_orders_v2_daily_snapshot
      - name: b2b_core_merchant_orders_v2_daily_snapshot
      - name: b2b_core_popup_requests_daily_snapshot
      - name: b2b_core_rfq_request_daily_snapshot
      - name: b2b_core_rfq_response_daily_snapshot
      - name: b2b_core_customers_daily_snapshot
      - name: b2b_core_merchant_appendixes_daily_snapshot
      - name: b2b_core_amo_crm_calls_daily_snapshot
      - name: b2b_core_merchants_daily_snapshot
      - name: b2b_core_rfq_media_uploads_daily_snapshot
      - name: b2b_core_stores_daily_snapshot
      - name: b2b_core_admin_user_plans_daily_snapshot
      - name: b2b_core_pick_up_orders_v2_daily_snapshot
      - name: product_merchant_document_product_links_daily_snapshot
      - name: core_merchant_documents_daily_snapshot
      - name: b2b_core_interactions_daily_snapshot
      - name: product_fast_delivery_info_daily_snapshot
      - name: logistics_customer_features_daily_snapshot
      - name: b2b_core_form_with_status_daily_snapshot
      - name: b2b_core_order_products_daily_snapshot
      - name: product_products_daily_snapshot
      - name: abu_core_brands_daily_snapshot
      - name: core_merchant_payment_channels_daily_snapshot
      - name: babylone_joom_tags_daily_snapshot
      - name: babylone_logistics_queues_daily_snapshot
      - name: babylone_logistics_tags_daily_snapshot
      - name: babylone_joom_queues_daily_snapshot
      - name: babylone_narwhal_queues_daily_snapshot
      - name: babylone_onfy_queues_daily_snapshot
      - name: babylone_narwhal_tags_daily_snapshot
      - name: babylone_onfy_tags_daily_snapshot
      - name: babylone_joom_tag_categories_daily_snapshot
      - name: babylone_logistics_tag_categories_daily_snapshot
      - name: babylone_narwhal_tag_categories_daily_snapshot
      - name: babylone_onfy_tag_categories_daily_snapshot
      - name: b2b_core_promocodes_daily_snapshot
      - name: b2b_core_issues_daily_snapshot
      - name: b2b_core_customer_plans_daily_snapshot
      - name: babylone_joom_agents_daily_snapshot
      - name: user_points_transactions_daily_snapshot
      - name: finance_order_costs_daily_snapshot
  - name: default
    tables:
      - name: sat_store_performance
  - name: b2b_mart
    tables:
      - name: device_events
      - name: operational_events
      - name: dim_merchant
  - name: logistics_mart
    tables:
      - name: fact_order
  - name: payments
    tables:
      - name: card_bins_snapshot
      - name: checkout_data
      - name: country_filter
  - name: recom
    tables:
      - name: context_device_counters_v5
  - name: product
    tables:
      - name: diagnoses_changes
  - name: platform
    tables:
      - name: aws_service_costs
      - name: s3_file_usage
      - name: table_locations
      - name: s3_costs
      - name: s3_accesses_with_tables
      - name: s3_inventory_with_tables
      - name: context_product_counters_v5
  - name: pharmacy
    tables:
      - name: google_campaign_insights
      - name: fbads_adset_country_insights
      - name: partners_insights
  - name: onfy_mart
    tables:
      - name: device_events
      - name: devices_mart
      - name: ads_spends
      - name: auth_proxy_devices_without_bots
      - name: transactions
  - name: pharmacy_landing
    tables:
      - name: order
      - name: order_parcel
      - name: store
      - name: order_parcel_checkpoint
      - name: device
      - name: order_parcel_item
      - name: refund
      - name: billing_operation
      - name: medicine
      - name: manufacturer
      - name: product
  - name: onfy
    tables:
      - name: lndc_user_attribution
        description: Last paid source for a user / device
      - name: sources
        description: Traffic sources by device and session date
  - name: merchant
    tables:
      - name: dim_merchant_payment_channel
        description: Merchant payment channels
        columns:
          - name: id
            description: Payment channel id
          - name: merchant_id
            description: Merchant id
          - name: method_id
            description: Selected payment method id
          - name: type
            description: Payment channel type( 0 - default, 1 - JoomUSA, 2 - Hyperwallet)
          - name: status
            description: Payment channel status (0 - not configured, 1 - error, 2 - pending external, 3 - configured, 4 - deactivated)
          - name: error_reasons
            description: Payment channel error reasons (0 - KYC error, 1 - payment method error)
          - name: updated_time
            description: Updated time
  - name: threat
    tables:
      - name: bot_factors_onfy
  - name: support
    tables:
      - name: shiftbase_rosters_snapshot_2023
      - name: shiftbase_users
      - name: shiftbase_teams
      - name: cbr_currency_rate 
  - name: push
    tables:
      - name: sale_dates_v1
