version: 2

sources:
  - name: mart
    tables:
      - name: dim_device_min
      - name: device_events
      - name: dim_published_variant
  - name: mongo
    tables:
      - name: b2b_core_users_daily_snapshot
      - name: b2b_core_published_products_daily_snapshot
      - name: b2b_core_product_states_daily_snapshot
      - name: b2b_core_product_appendixes_daily_snapshot
      - name: b2b_core_orders_v2_daily_snapshot
      - name: b2b_core_popup_requests_daily_snapshot
      - name: product_merchant_document_product_links_daily_snapshot
      - name: core_merchant_documents_daily_snapshot
  - name: default
    tables:
      - name: mongo_merchant
  - name: b2b_mart
    tables:
      - name: device_events
      - name: operational_events
      