version: 2

sources:
  - name: mart
    tables:
      - name: dim_device_min
      - name: device_events
      - name: dim_published_variant
      - name: product_rating_counters
      - name: star_order_2020
      - name: star_active_device
      - name: category_levels
      - name: dim_published_product_min
      - name: core_review_quiz_answers_scd2
      - name: babylone_events
      - name: fact_order_2020
  - name: mongo
    tables:
      - name: core_categories_daily_snapshot
      - name: core_experiments_daily_snapshot
      - name: core_stores_daily_snapshot
      - name: events_ad_spent_internal_daily_snapshot
      - name: events_ad_partners_daily_snapshot
      - name: core_tracking_providers_daily_snapshot
      - name: core_merchants_daily_snapshot
      - name: b2b_core_users_daily_snapshot
      - name: b2b_core_admin_users_daily_snapshot
      - name: b2b_core_variant_appendixes_daily_snapshot
      - name: b2b_core_published_products_daily_snapshot
      - name: b2b_core_published_variants_daily_snapshot
      - name: b2b_core_product_states_daily_snapshot
      - name: b2b_core_product_appendixes_daily_snapshot
      - name: b2b_core_orders_v2_daily_snapshot
      - name: b2b_core_merchant_orders_v2_daily_snapshot
      - name: b2b_core_popup_requests_daily_snapshot
      - name: b2b_core_rfq_request_daily_snapshot
      - name: b2b_core_rfq_response_daily_snapshot
      - name: b2b_core_customers_daily_snapshot
      - name: product_merchant_document_product_links_daily_snapshot
      - name: core_merchant_documents_daily_snapshot
  - name: default
    tables:
      - name: sat_store_performance
  - name: b2b_mart
    tables:
      - name: device_events
      - name: operational_events
  - name: logistics_mart
    tables:
      - name: fact_order
  - name: support
    tables:
      - name: support_mart_ticket_id_ext
