version: 2

sources:
  - name: productsmatching
    tables:
      - name: joom_1688_product_variant_matches
  - name: mongo
    tables:
      - name: b2b_core_users_daily_snapshot
      - name: b2b_core_admin_users_daily_snapshot
      - name: b2b_product_variant_appendixes_daily_snapshot
      - name: b2b_product_published_products_daily_snapshot
      - name: b2b_product_published_variants_daily_snapshot
      - name: b2b_product_product_states_daily_snapshot
      - name: b2b_product_product_appendixes_daily_snapshot
      - name: b2b_core_orders_v2_daily_snapshot
      - name: b2b_core_merchant_orders_v2_daily_snapshot
      - name: b2b_core_popup_requests_daily_snapshot
      - name: b2b_core_rfq_request_daily_snapshot
      - name: b2b_core_rfq_response_daily_snapshot
      - name: b2b_core_customers_daily_snapshot
      - name: b2b_core_merchant_appendixes_daily_snapshot
      - name: b2b_core_amo_crm_calls_daily_snapshot
      - name: b2b_core_merchants_daily_snapshot
      - name: b2b_core_rfq_media_uploads_daily_snapshot
      - name: b2b_core_stores_daily_snapshot
      - name: b2b_core_admin_user_plans_daily_snapshot
      - name: b2b_core_admin_user_sdr_plans_daily_snapshot
      - name: b2b_core_pick_up_orders_v2_daily_snapshot
      - name: b2b_core_amo_crm_raw_leads_daily_snapshot
      - name: b2b_core_enumregistry_daily_snapshot
      - name: b2b_core_merchant_attributes_daily_snapshot
      - name: b2b_core_deals_daily_snapshot
      - name: b2b_core_analytics_users_daily_snapshot
      - name: b2b_core_analytics_users_extras_daily_snapshot
      - name: b2b_core_blog_subscriptions_daily_snapshot
      - name: b2b_core_calculations_daily_snapshot
      - name: b2b_core_interactions_daily_snapshot
      - name: b2b_core_form_with_status_daily_snapshot
      - name: b2b_core_order_products_daily_snapshot
      - name: b2b_core_phone_credentials_daily_snapshot
      - name: b2b_core_analytics_phone_credentials_daily_snapshot
      - name: b2b_core_promocodes_daily_snapshot
      - name: b2b_core_issues_daily_snapshot
      - name: b2b_core_customer_plans_daily_snapshot
      - name: b2b_core_customer_offers_daily_snapshot
      - name: b2b_core_customer_rfq_response_v2_daily_snapshot
      - name: b2b_core_customer_rfq_request_daily_snapshot
      - name: b2b_core_customer_requests_daily_snapshot
      - name: b2b_core_offer_products_daily_snapshot
      - name: b2b_core_analytics_payments_daily_snapshot
      - name: b2b_core_sla_trackers_daily_snapshot
      - name: b2b_product_product_jpa_matches_daily_snapshot
      - name: b2b_core_analytics_subscriptions_daily_snapshot
      - name: b2b_product_product_prices_daily_snapshot
      - name: b2b_core_promotions_daily_snapshot
      - name: b2b_core_promo_product_groups_daily_snapshot
      - name: b2b_core_quotes_daily_snapshot
      - name: b2b_core_i18ndata_daily_snapshot
      - name: b2b_core_merchant_kyc_profiles_daily_snapshot
  - name: b2b_mart
    tables:
      - name: device_events
      - name: operational_events
      - name: dim_merchant
      - name: merchants
      - name: merchant_products
      - name: ss_assortment_products
      - name: fact_customer_requests
      - name: ss_events_customer_journey
      - name: ss_events_by_session
      - name: ss_users_table
      - name: fact_customer_requests_variants
      - name: fact_deals_with_requests
  - name: joompro_analytics
    tables:
      - name: mercadolibre_category_info
  
