version: 2

models:
  - name: table_in_bq
    description: Testing if comments are updated in BQ table
    columns:
      - name: num_field
        description: This field contains numbers
      - name: str_field
        description: This one contains strings
