# This is config for different dag. Contains params for each dag. If param doesn't set
# explicit in dag section then will be used default param.
# Available params:
# - dag-name - name of the dag
# - dag-tags - tags for dag (airflow tags)
# - crontab - schedule for dag
# - alerts-channel - channel for alerts
# - profiles-dir - dir with dbt profiles
# - profile-name - using profile
# - tags - tags for filter. If model contain multiply tags, then will be using the last one

default:
  dag-name: dbt-etl
  crontab: 15 0 * * * 
  alerts-channel: "#dbt-spark-monitoring"
  profiles-dir: "production/profiles"
  profile-name: spark
  excluded-tags: ["manual"]
  slo-hour: 18
platform:
  dag-name: dbt-platform
  alerts-channel: "#analytics-monitoring"
  tags: ["platform"]
data-readiness:
  dag-name: data-readiness
  crontab: 0 * * * *
  alerts-channel: "#analytics-monitoring"
  tags: ["data_readiness"]
b2b-mart:
  dag-name: b2b-marts
  alerts-channel: "#alerts-pro-dbt"
  tags: ["b2b_mart"]
onfy:
  dag-name: onfy
  alerts-channel: "#onfy-etl-monitoring"
  tags: ["onfy"]
  slo-hour: 15
pulse:
  dag-name: pulse
  dag-tags: ["joom_pulse"]
  crontab: 0 9 * * *
  alerts-channel: "#pulse-data-monitoring"
  tags: ["pulse"]
  slo-hour: 15
gold:
  dag-name: gold
  profile-name: gold
  alerts-channel: "#dbt-spark-monitoring"
  tags: ["gold"]
  slo-hour: 8
