sources:
  - name: onfy
    tables:
      - name: onfy_sessions
      - name: search_serp_requests_i
      - name: search_serp_items_i
  - name: pharmacy_landing
    tables:
      - name: product_category_flat
      - name: category
      - name: checkout
      - name: order_paketshop
      - name: medicine_ingredient
      - name: ingredient
      - name: dosage_form
      - name: order_parcel_delivery
      - name: price_applier_applied_for_object
  - name: pharmacy
    tables:
      - name: bing_partner_insights
      - name: criteo_insights
      - name: google_campaign_insights
      - name: fbads_adset_country_insights
      - name: adjust_raw_network_insights
      - name: partners_insights
      - name: mindbox_events
      - name: awin_insights
      - name: adjust_report_deliverables_insights
      - name: adjust_report_cohort_insights
      - name: marketing_channel_price_fast_scd2
      - name: mindbox_events_v2
      - name: feed_loaders_state
      - name: product_store_fast_scd2
  
