sources:
  - name: onfy
    tables:
      - name: orders_info
      - name: sessions
  - name: pharmacy_landing
    tables:
      - name: product_category_flat
      - name: category
      - name: checkout
      - name: order_paketshop
      - name: medicine_ingredient
      - name: ingredient
      - name: dosage_form
