sources:
  - name: onfy
    tables:
      - name: orders_info
      - name: sessions
      - name: onfy_medicine_analogs
      - name: conversion_funnel_new
      - name: ads_dashboard
      - name: refunds
      - name: auto_discount_rules
  - name: pharmacy_landing
    tables:
      - name: product_category_flat
      - name: category
      - name: checkout
      - name: order_paketshop
      - name: medicine_ingredient
      - name: ingredient
      - name: dosage_form
      - name: order_parcel_delivery
  - name: pharmacy
    tables:
      - name: bing_partner_insights
      - name: adjust_raw_cohort_insights
      - name: adjust_raw_deliverables_insights
      - name: criteo_insights
      - name: google_campaign_insights
      - name: fbads_adset_country_insights
      - name: adjust_raw_network_insights
      - name: partners_insights
      - name: mindbox_events
      - name: awin_insights
