{% snapshot scd2_retargeting_last_click_roas_by_adjust %}

{{
    config(
      target_schema='ads_models',
      unique_key='id',
      strategy='check',
      check_cols='all',
      file_format='delta',
      invalidate_hard_deletes=True,
      meta = {
      'model_owner' : '@zhabrev',
          'team' : 'advertising',
      }
    )
}}

    SELECT
        CONCAT(
            CAST(partition_date AS STRING),
            '-',
            COALESCE(source, 'source'),
            '-',
            COALESCE(campaign_id, 'campaign_id'),
            '-',
            COALESCE(country, 'country'),
            '-',
            CAST(is_inactive_audience AS STRING),
            '-',
            COALESCE(audience_name, 'audience_name'),
            '-',
            COALESCE(campaign_name, 'campaign_name')
        ) AS id,

        partition_date,
        source,
        campaign_id,
        country,
        is_inactive_audience,
        audience_name,
        campaign_name,

        ROUND(spend, 2) AS spend,
        ROUND(gmv1d, 2) AS gmv1d,
        ROUND(gmv7d, 2) AS gmv7d,
        ROUND(gmv7d_estimated_raw, 2) AS gmv7d_estimated_raw,
        ROUND(gp_margin_lag1w, 2) AS gp_margin_lag1w,
        ROUND(e_gmv7d, 2) AS e_gmv7d,
        ROUND(country_gp_margin_lag1w, 2) AS country_gp_margin_lag1w,
        ROUND(gmv1d_to_7d_lag1w, 2) AS gmv1d_to_7d_lag1w,
        ROUND(campaign_gp_margin_lag1w, 2) AS campaign_gp_margin_lag1w,
        ROUND(cart_purchase_gp_1d, 2) AS cart_purchase_gp_1d,
        ROUND(cart_purchase_gp_28d, 2) AS cart_purchase_gp_28d,
        ROUND(cart_purchase_gp_21d, 2) AS cart_purchase_gp_21d,
        ROUND(cart_purchase_gp_14d, 2) AS cart_purchase_gp_14d,
        ROUND(cart_purchase_gp_7d, 2) AS cart_purchase_gp_7d,
        ROUND(gmv28d, 2) AS gmv28d,
        ROUND(gmv21d, 2) AS gmv21d,
        ROUND(gmv14d, 2) AS gmv14d,
        ROUND(device_ads_click_order_groups_28d, 2) AS device_ads_click_order_groups_28d,
        ROUND(device_click_order_groups_28d, 2) AS device_click_order_groups_28d,
        ROUND(device_click_gmv1d, 2) AS device_click_gmv1d,
        ROUND(device_click_order_groups_7d, 2) AS device_click_order_groups_7d,
        ROUND(real_user_click_gmv7d, 2) AS real_user_click_gmv7d,
        ROUND(device_ads_click_gmv28d, 2) AS device_ads_click_gmv28d,
        ROUND(device_click_order_groups_1d, 2) AS device_click_order_groups_1d,
        ROUND(device_click_gmv14d, 2) AS device_click_gmv14d,
        ROUND(device_ads_click_gp14d, 2) AS device_ads_click_gp14d,
        ROUND(real_user_click_order_groups_28d, 2) AS real_user_click_order_groups_28d,
        ROUND(device_click_gmv7d, 2) AS device_click_gmv7d,
        ROUND(real_user_click_gmv14d, 2) AS real_user_click_gmv14d,
        ROUND(device_click_gp7d, 2) AS device_click_gp7d,
        ROUND(device_click_gp14d, 2) AS device_click_gp14d,
        ROUND(device_ads_click_gp1d, 2) AS device_ads_click_gp1d,
        ROUND(device_ads_click_gmv7d, 2) AS device_ads_click_gmv7d,
        ROUND(device_ads_click_gmv14d, 2) AS device_ads_click_gmv14d,
        ROUND(device_click_gmv28d, 2) AS device_click_gmv28d,
        ROUND(real_user_click_order_groups_7d, 2) AS real_user_click_order_groups_7d,
        ROUND(device_ads_click_order_groups_7d, 2) AS device_ads_click_order_groups_7d,
        ROUND(real_user_click_order_groups_14d, 2) AS real_user_click_order_groups_14d,
        ROUND(real_user_click_gmv1d, 2) AS real_user_click_gmv1d,
        ROUND(device_click_gp1d, 2) AS device_click_gp1d,
        ROUND(device_click_clicks, 2) AS device_click_clicks,
        ROUND(real_user_click_gmv28d, 2) AS real_user_click_gmv28d,
        ROUND(device_click_order_groups_14d, 2) AS device_click_order_groups_14d,
        ROUND(device_ads_click_gmv1d, 2) AS device_ads_click_gmv1d,
        ROUND(real_user_click_gp1d, 2) AS real_user_click_gp1d,
        ROUND(device_ads_click_gp7d, 2) AS device_ads_click_gp7d,
        ROUND(real_user_click_gp28d, 2) AS real_user_click_gp28d,
        ROUND(device_ads_click_gp28d, 2) AS device_ads_click_gp28d,
        ROUND(real_user_click_order_groups_1d, 2) AS real_user_click_order_groups_1d,
        ROUND(device_ads_click_order_groups_14d, 2) AS device_ads_click_order_groups_14d,
        ROUND(real_user_click_gp7d, 2) AS real_user_click_gp7d,
        ROUND(real_user_click_clicks, 2) AS real_user_click_clicks,
        ROUND(device_ads_click_clicks, 2) AS device_ads_click_clicks,
        ROUND(real_user_click_gp14d, 2) AS real_user_click_gp14d,
        ROUND(device_ads_click_order_groups_1d, 2) AS device_ads_click_order_groups_1d,
        ROUND(device_click_gp28d, 2) AS device_click_gp28d,
        ROUND(country_cart_purchase_gp7_to_28d_lag3w, 2) AS country_cart_purchase_gp7_to_28d_lag3w,
        ROUND(roi7d_target, 2) AS roi7d_target,
        ROUND(roi_7_to_28d, 2) AS roi_7_to_28d,
        ROUND(source_cart_purchase_gp7_to_28d_lag3w, 2) AS source_cart_purchase_gp7_to_28d_lag3w,
        ROUND(campaign_cart_purchase_gp7_to_28d_lag3w, 2) AS campaign_cart_purchase_gp7_to_28d_lag3w,
        ROUND(roi7d_target_raw, 2) AS roi7d_target_raw,
        ROUND(gmv7d_estimated_1d_raw, 2) AS gmv7d_estimated_1d_raw,
        ROUND(gmv7d_estimated_2d_raw, 2) AS gmv7d_estimated_2d_raw,
        ROUND(e_gp1d, 2) AS e_gp1d,
        ROUND(e_gp7d, 2) AS e_gp7d,
        ROUND(gmv2d, 2) AS gmv2d,
        ROUND(gmv2d_to_7d_lag1w, 2) AS gmv2d_to_7d_lag1w,
        ROUND(cart_purchase_gp_2d, 2) AS cart_purchase_gp_2d,
        ROUND(gp7d_target, 2) AS gp7d_target,
        ROUND(source_gp_margin_lag1w, 2) AS source_gp_margin_lag1w,
        ROUND(device_ads_click_with_san_gp28d, 2) AS device_ads_click_with_san_gp28d,
        ROUND(device_ads_click_with_san_gmv1d, 2) AS device_ads_click_with_san_gmv1d,
        ROUND(device_ads_click_with_san_gp14d, 2) AS device_ads_click_with_san_gp14d,
        ROUND(device_ads_click_with_san_order_groups_14d, 2) AS device_ads_click_with_san_order_groups_14d,
        ROUND(device_ads_click_with_san_gmv28d, 2) AS device_ads_click_with_san_gmv28d,
        ROUND(device_ads_click_with_san_clicks, 2) AS device_ads_click_with_san_clicks,
        ROUND(device_ads_click_with_san_gp1d, 2) AS device_ads_click_with_san_gp1d,
        ROUND(device_ads_click_with_san_gp7d, 2) AS device_ads_click_with_san_gp7d,
        ROUND(device_ads_click_with_san_order_groups_1d, 2) AS device_ads_click_with_san_order_groups_1d,
        ROUND(device_ads_click_with_san_gmv14d, 2) AS device_ads_click_with_san_gmv14d,
        ROUND(device_ads_click_with_san_order_groups_7d, 2) AS device_ads_click_with_san_order_groups_7d,
        ROUND(device_ads_click_with_san_gmv7d, 2) AS device_ads_click_with_san_gmv7d,
        ROUND(device_ads_click_with_san_order_groups_28d, 2) AS device_ads_click_with_san_order_groups_28d,
        ROUND(device_ads_click_with_san_6h_order_groups_28d, 2) AS device_ads_click_with_san_6h_order_groups_28d,
        ROUND(device_ads_click_with_san_6h_order_groups_7d, 2) AS device_ads_click_with_san_6h_order_groups_7d,
        ROUND(device_ads_click_with_san_24h_gp14d, 2) AS device_ads_click_with_san_24h_gp14d,
        ROUND(device_ads_click_with_san_24h_gp1d, 2) AS device_ads_click_with_san_24h_gp1d,
        ROUND(device_ads_click_with_san_24h_order_groups_1d, 2) AS device_ads_click_with_san_24h_order_groups_1d,
        ROUND(device_ads_click_with_san_24h_gp7d, 2) AS device_ads_click_with_san_24h_gp7d,
        ROUND(device_ads_click_with_san_6h_order_groups_1d, 2) AS device_ads_click_with_san_6h_order_groups_1d,
        ROUND(device_ads_click_with_san_6h_order_groups_14d, 2) AS device_ads_click_with_san_6h_order_groups_14d,
        ROUND(device_ads_click_with_san_6h_gmv28d, 2) AS device_ads_click_with_san_6h_gmv28d,
        ROUND(device_ads_click_with_san_6h_gmv14d, 2) AS device_ads_click_with_san_6h_gmv14d,
        ROUND(device_ads_click_with_san_6h_gp7d, 2) AS device_ads_click_with_san_6h_gp7d,
        ROUND(device_ads_click_with_san_24h_clicks, 2) AS device_ads_click_with_san_24h_clicks,
        ROUND(device_ads_click_with_san_24h_order_groups_28d, 2) AS device_ads_click_with_san_24h_order_groups_28d,
        ROUND(device_ads_click_with_san_24h_gmv7d, 2) AS device_ads_click_with_san_24h_gmv7d,
        ROUND(device_ads_click_with_san_24h_order_groups_7d, 2) AS device_ads_click_with_san_24h_order_groups_7d,
        ROUND(device_ads_click_with_san_24h_gp28d, 2) AS device_ads_click_with_san_24h_gp28d,
        ROUND(device_ads_click_with_san_6h_clicks, 2) AS device_ads_click_with_san_6h_clicks,
        ROUND(device_ads_click_with_san_6h_gmv7d, 2) AS device_ads_click_with_san_6h_gmv7d,
        ROUND(device_ads_click_with_san_24h_gmv1d, 2) AS device_ads_click_with_san_24h_gmv1d,
        ROUND(device_ads_click_with_san_6h_gp1d, 2) AS device_ads_click_with_san_6h_gp1d,
        ROUND(device_ads_click_with_san_24h_gmv28d, 2) AS device_ads_click_with_san_24h_gmv28d,
        ROUND(device_ads_click_with_san_24h_gmv14d, 2) AS device_ads_click_with_san_24h_gmv14d,
        ROUND(device_ads_click_with_san_6h_gp14d, 2) AS device_ads_click_with_san_6h_gp14d,
        ROUND(device_ads_click_with_san_24h_order_groups_14d, 2) AS device_ads_click_with_san_24h_order_groups_14d,
        ROUND(device_ads_click_with_san_6h_gp28d, 2) AS device_ads_click_with_san_6h_gp28d,
        ROUND(device_ads_click_with_san_6h_gmv1d, 2) AS device_ads_click_with_san_6h_gmv1d,
        ROUND(country_gmv2d_to_7d_lag1w, 2) AS country_gmv2d_to_7d_lag1w,
        ROUND(campaign_gmv1d_to_7d_lag1w, 2) AS campaign_gmv1d_to_7d_lag1w,
        ROUND(country_gmv1d_to_7d_lag1w, 2) AS country_gmv1d_to_7d_lag1w,
        ROUND(campaign_gmv2d_to_7d_lag1w, 2) AS campaign_gmv2d_to_7d_lag1w,
        ROUND(source_gmv2d_to_7d_lag1w, 2) AS source_gmv2d_to_7d_lag1w,
        ROUND(source_gmv1d_to_7d_lag1w, 2) AS source_gmv1d_to_7d_lag1w
    FROM {{ source('ads', 'retargeting_last_click_roas_by_adjust') }}
    WHERE
        CONCAT(
            CAST(partition_date AS STRING),
            '-',
            COALESCE(source, 'source'),
            '-',
            COALESCE(campaign_id, 'campaign_id'),
            '-',
            COALESCE(country, 'country'),
            '-',
            CAST(is_inactive_audience AS STRING),
            '-',
            COALESCE(audience_name, 'audience_name'),
            '-',
            COALESCE(campaign_name, 'campaign_name')
        ) IS NOT NULL

{% endsnapshot %}
