spark:
  target: prod
  outputs:
    prod:
      host: thrift-service-prod.joom.ai
      method: thrift
      port: 10000
      schema: models
      threads: 1
      type: spark
gold:
  target: prod
  outputs:
    prod:
      host: thrift-service-gold.thrift-service.svc
      method: thrift
      port: 10000
      schema: models
      threads: 1
      type: spark
