version: 2

sources:
  - name: ads
    tables:
      - name: web_analytics_cohorts_v4
      - name: referral_payout_stats
      - name: referral_bloggers
      - name: web_analytics_pageviews_with_segments
  - name: mart
    tables:
      - name: dim_device_min
      - name: dim_product
      - name: device_events
      - name: product_rating_counters
      - name: star_order_2020
      - name: star_active_device
      - name: category_levels
      - name: dim_published_product_min
      - name: core_review_quiz_answers_scd2
      - name: babylone_events
      - name: fact_order_2020
      - name: published_products_current
      - name: onfy_babylone_events
      - name: dim_currency_rate
      - name: product_events
      - name: promotions
      - name: dim_merchant
      - name: dim_date
      - name: dim_pair_currency_rate
  - name: cube
    tables:
      - name: event_counts_country_os_days
      - name: time_orders_additional_cube_2_days
  - name: mongo
    tables:
      - name: core_categories_daily_snapshot
      - name: core_experiments_daily_snapshot
      - name: core_stores_daily_snapshot
      - name: events_ad_spent_internal_daily_snapshot
      - name: events_ad_partners_daily_snapshot
      - name: core_tracking_providers_daily_snapshot
      - name: core_merchants_daily_snapshot
      - name: b2b_core_users_daily_snapshot
      - name: b2b_core_admin_users_daily_snapshot
      - name: b2b_core_variant_appendixes_daily_snapshot
      - name: b2b_core_published_products_daily_snapshot
      - name: b2b_core_published_variants_daily_snapshot
      - name: b2b_core_product_states_daily_snapshot
      - name: b2b_core_product_appendixes_daily_snapshot
      - name: b2b_core_orders_v2_daily_snapshot
      - name: b2b_core_merchant_orders_v2_daily_snapshot
      - name: b2b_core_popup_requests_daily_snapshot
      - name: b2b_core_rfq_request_daily_snapshot
      - name: b2b_core_rfq_response_daily_snapshot
      - name: b2b_core_customers_daily_snapshot
      - name: b2b_core_merchant_appendixes_daily_snapshot
      - name: b2b_core_amo_crm_calls_daily_snapshot
      - name: b2b_core_merchants_daily_snapshot
      - name: b2b_core_rfq_media_uploads_daily_snapshot
      - name: b2b_core_stores_daily_snapshot
      - name: b2b_core_admin_user_plans_daily_snapshot
      - name: b2b_core_admin_user_sdr_plans_daily_snapshot
      - name: b2b_core_pick_up_orders_v2_daily_snapshot
      - name: b2b_core_amo_crm_raw_leads_daily_snapshot
      - name: b2b_core_enumregistry_daily_snapshot
      - name: b2b_core_merchant_attributes_daily_snapshot
      - name: b2b_core_deals_daily_snapshot
      - name: b2b_core_analytics_users_daily_snapshot
      - name: b2b_core_calculations_daily_snapshot
      - name: product_merchant_document_product_links_daily_snapshot
      - name: core_merchant_documents_daily_snapshot
      - name: core_store_specializations_daily_snapshot
      - name: b2b_core_interactions_daily_snapshot
      - name: product_fast_delivery_info_daily_snapshot
      - name: logistics_customer_features_daily_snapshot
      - name: b2b_core_form_with_status_daily_snapshot
      - name: b2b_core_order_products_daily_snapshot
      - name: b2b_core_phone_credentials_daily_snapshot
      - name: product_products_daily_snapshot
      - name: abu_core_brands_daily_snapshot
      - name: core_merchant_payment_channels_daily_snapshot
      - name: babylone_joom_tags_daily_snapshot
      - name: babylone_logistics_queues_daily_snapshot
      - name: babylone_logistics_tags_daily_snapshot
      - name: babylone_onfy_queues_daily_snapshot
      - name: babylone_onfy_tags_daily_snapshot
      - name: babylone_joom_tag_categories_daily_snapshot
      - name: babylone_logistics_tag_categories_daily_snapshot
      - name: babylone_onfy_tag_categories_daily_snapshot
      - name: b2b_core_promocodes_daily_snapshot
      - name: b2b_core_issues_daily_snapshot
      - name: b2b_core_customer_plans_daily_snapshot
      - name: b2b_core_customer_offers_daily_snapshot
      - name: b2b_core_customer_rfq_response_v2_daily_snapshot
      - name: b2b_core_customer_rfq_request_daily_snapshot
      - name: b2b_core_customer_requests_daily_snapshot
      - name: b2b_core_offer_products_daily_snapshot
      - name: babylone_joom_agents_daily_snapshot
      - name: points_points_transactions_daily_snapshot
      - name: finance_order_costs_daily_snapshot
      - name: babylone_logistics_agents_daily_snapshot
      - name: babylone_onfy_agents_daily_snapshot
      - name: logistics_jl_obligatory_channels_daily_snapshot
      - name: abu_core_catalog_daily_snapshot
  - name: default
    tables:
      - name: sat_store_performance
      - name: productsGroups_louvain
      - name: link_device_user
      - name: link_device_real_user
  - name: b2b_mart
    tables:
      - name: device_events
      - name: operational_events
      - name: dim_merchant
  - name: logistics_mart
    tables:
      - name: fact_order
      - name: tariffs
  - name: payments
    tables:
      - name: card_bins_snapshot
      - name: country_filter
      - name: card_bins
      - name: chargeback
      - name: fact_refund
      - name: order_groups
      - name: payment
      - name: payment_order
  - name: recom
    tables:
      - name: context_device_counters_v6
  - name: product
    tables:
      - name: diagnoses_changes
  - name: platform
    tables:
      - name: aws_service_costs
      - name: s3_costs
      - name: s3_accesses_with_tables
      - name: s3_inventory_with_tables
      - name: context_product_counters_v5
      - name: fact_removed_device_event
  - name: pharmacy
    tables:
      - name: fbads_adset_country_insights
  - name: onfy_mart
    tables:
      - name: device_events
      - name: devices_mart
      - name: ads_spends
      - name: auth_proxy_devices_without_bots
      - name: transactions
      - name: dim_product
  - name: pharmacy_landing
    tables:
      - name: order
      - name: order_parcel
      - name: store
      - name: store_delivery
      - name: order_parcel_checkpoint
      - name: device
      - name: order_parcel_item
      - name: refund
      - name: refund_order_parcel
      - name: refund_order_parcel_item
      - name: billing_operation
      - name: medicine
      - name: manufacturer
      - name: product
      - name: promocode
      - name: admin_user
  - name: onfy
    tables:
      - name: lndc_user_attribution
        description: Last paid source for a user / device
      - name: sources
        description: Traffic sources by device and session date
      - name: transactions
        description: Main financial source
      - name: conversion_funnel
        description: Onfy main stages conversion rates
  - name: threat
    tables:
      - name: bot_factors_onfy
  - name: push
    tables:
      - name: sale_dates_v1
  - name: experiments
    tables:
      - name: experiments_setup
      - name: rollout_group
  - name: mi_analytics
    tables:
      - name: aliexpress_logistics_prices

  - name: goods
    tables:
      - name: coolbe_product_labels

