version: 2

sources:
  - name: ads
    tables:
      - name: referral_payout_stats
      - name: referral_bloggers
      - name: web_analytics_pageviews_with_segments
      - name: ads_install
      - name: product_availability
  - name: mart
    tables:
      - name: dim_device_min
      - name: dim_product
      - name: device_events
      - name: product_rating_counters
      - name: star_order_2020
      - name: star_active_device
      - name: category_levels
      - name: dim_published_product_min
      - name: core_review_quiz_answers_scd2
      - name: babylone_events
      - name: fact_order_2020
      - name: published_products_current
      - name: dim_currency_rate
      - name: onfy_babylone_events
      - name: product_events
      - name: promotions
      - name: dim_merchant
      - name: dim_date
      - name: dim_pair_currency_rate
      - name: dim_published_variant_with_merchant
      - name: dim_joom_select_proposal
      - name: dim_product_review
      - name: unclassified_events
      
  - name: cube
    tables:
      - name: event_counts_country_os_days
      - name: time_orders_additional_cube_2_days
      - name: profit
  - name: mongo
    tables:
      - name: core_categories_daily_snapshot
      - name: core_experiments_daily_snapshot
      - name: core_stores_daily_snapshot
      - name: events_ad_spent_internal_daily_snapshot
      - name: events_ad_partners_daily_snapshot
      - name: core_tracking_providers_daily_snapshot
      - name: core_merchants_daily_snapshot
      - name: product_merchant_document_product_links_daily_snapshot
      - name: product_product_document_links_daily_snapshot
      - name: product_product_diagnoses_daily_snapshot
      - name: core_merchant_documents_daily_snapshot
      - name: core_store_specializations_daily_snapshot
      - name: product_products_daily_snapshot
      - name: abu_core_brands_daily_snapshot
      - name: core_merchant_payment_channels_daily_snapshot
      - name: babylone_joom_tags_daily_snapshot
      - name: babylone_logistics_queues_daily_snapshot
      - name: babylone_logistics_tags_daily_snapshot
      - name: babylone_onfy_tags_daily_snapshot
      - name: babylone_joom_tag_categories_daily_snapshot
      - name: babylone_logistics_tag_categories_daily_snapshot
      - name: babylone_joom_agents_daily_snapshot
      - name: points_points_transactions_daily_snapshot
      - name: finance_order_costs_daily_snapshot
      - name: babylone_logistics_agents_daily_snapshot
      - name: logistics_jl_obligatory_channels_daily_snapshot
      - name: abu_core_catalog_daily_snapshot
      - name: product_merchant_joom_select_proposals_daily_snapshot
      - name: core_paid_post_tenders_daily_snapshot
      - name: user_paid_post_bids_daily_snapshot
      - name: social_social_users_daily_snapshot
      - name: merchant_order_orders_daily_snapshot
      - name: merchant_order
      - name: logistics_product_stocks_daily_snapshot
      - name: logistics_products_v2_daily_snapshot
      - name: logistics_warehouse_product_infos_daily_snapshot
      - name: core_merchant_fines_daily_snapshot
      - name: logistics_zipcode_range_snapshots_daily_snapshot
      - name: logistics_pickup_orders_daily_snapshot
      - name: core_fbj_replenishments_daily_snapshot
      - name: product_fbj_demand_sk_us_daily_snapshot
      - name: logistics_replenishments_v3_daily_snapshot
      - name: product_committed_fulfillment_daily_snapshot
      - name: logistics_bags_daily_snapshot
      - name: logistics_channels_daily_snapshot 
  - name: default
    tables:
      - name: sat_store_performance
      - name: productsGroups_louvain
      - name: link_device_user
      - name: link_device_real_user
  - name: logistics_mart
    tables:
      - name: fact_order
      - name: tariffs
  - name: payments
    tables:
      - name: card_bins_snapshot
      - name: country_filter
      - name: card_bins
      - name: chargeback
      - name: fact_refund
      - name: payment
      - name: payment_order
      - name: order_groups
  - name: recom
    tables:
      - name: context_device_counters_v6
  - name: platform
    tables:
      - name: aws_service_costs
      - name: s3_costs
      - name: s3_accesses_with_tables
      - name: s3_inventory_with_tables
      - name: context_product_counters_v5
      - name: fact_removed_device_event
      - name: table_dependencies_v2
      - name: table_producers
  - name: onfy_mart
    tables:
      - name: device_events
      - name: devices_mart
      - name: ads_spends
      - name: auth_proxy_devices_without_bots
      - name: transactions
      - name: dim_product
  - name: pharmacy_landing
    tables:
      - name: order
      - name: order_parcel
      - name: store
      - name: store_delivery
      - name: order_parcel_checkpoint
      - name: device
      - name: order_parcel_item
      - name: refund
      - name: refund_order_parcel
      - name: refund_order_parcel_item
      - name: medicine
      - name: manufacturer
      - name: product
      - name: promocode
      - name: admin_user
  - name: onfy
    tables:
      - name: lndc_user_attribution
        description: Last paid source for a user / device
      - name: sources
        description: Traffic sources by device and session date
      - name: transactions
        description: Main financial source
      - name: conversion_funnel
        description: Onfy main stages conversion rates
  - name: threat
    tables:
      - name: bot_factors_onfy
      - name: bot_factors_joompro
  - name: push
    tables:
      - name: sale_dates_v1
  - name: experiments
    tables:
      - name: experiments_setup
      - name: rollout_group_2
  - name: mi_analytics
    tables:
      - name: aliexpress_logistics_prices
      - name: aliexpress_joom_price_index_v2

  - name: goods
    tables:
      - name: coolbe_product_labels
      - name: product_labels

  - name: joompro_mart
    tables:
      - name: mercadolibre_categories
      - name: mercadolibre_categories_view
      - name: auth_proxy_dim_devices
      - name: sellers_for_outreach
      - name: contacts_cpf
  
  - name: joompro_analytics_mart
    tables:
      - name: mercadolibre_products_snapshot
      - name: cube_mlb_products

  - name: joompro_analytics
    tables:
      - name: mercadolibre_categories_reviews_cube_js_weekly
      - name: mercadolibre_categories_cube_js_monthly
      - name: ods_mlb_mobile_api_product_previews

  - name: category_management
    tables:
      - name: joom_select_manual_criteria
      - name: js_merchant_discount_rate
      - name: joom_select_product_white_list
      - name: joom_select_product_black_list
      - name: categories_with_ce_requirements

  - name: merchant
    tables:
      - name: merchant_performance
      - name: order_data
